language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: onguntoglu
  password:
    secure: iO4Iv00v6tAcjXRYYGpI9fe8kCrhDgkD9/d7w+v1wrCYWWsKZpLJC0v3YGz4uDMnDlwqHUfIkw3WoKecS711Bd9BszT5umgWdcXMgnoEkSIpJiCtsuYqWM6WvNO9losvZ3QvE4SIsbvEyKl4cm2VLCpFlPfrLFf7pmA+7oOy3D3WXf6GIVdIXZvnZn/FAiRuOVsoAjWtLUC0D3Ftw3xfRFetNZk62dYN4Hna/ko9AFLKXlMHkK1fHY28o9r9GwUP2hxODe8gHsajrE0PVArRGawloQIoh5EH2WrFmoOQ5YY7Wn/KgSLxaRI7NXGhIobSrXC+hDl3UnZONR8TF9vHxYF8Sm+MtRxY/vYrs/C/nJuRsfE69JVO0rkstfyvt3nzzAZPvO3vkvFksHBlS2YC+MDO9V7wexEYCBLiGcjwSpgfKQdoQOcYGGCMUL1YhAUCu5R6bVrBHpreP7ACdnwhLi1XCDRInf2AhJMib5VOFFflUguQaGWzDRjUkMNCDda7o8WrfnazrMC4J95VH8IQyJlwLl4c7srlK+bhPTajO3HDFL1sAQww3B00SWYZI+IUH0Uvbau2JeEm6ODS2+579/uyiTFBofnTel+wqKXeDpchCZw9dPIAOCF0IWraI/TOF41K+LyhpDDcS9jZSqLgIhTDARtYO6bwnhw326dNV3E=
  on:
    tags: true
    repo: onguntoglu/pyadrc
    python: 3.8
