language: python
python:
- 3.8
- 3.7
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: onguntoglu
  password:
    secure: yjjZNXlAxBfpP+3PbF7P4wnevPIPt9rqWcVpggJv1bm27OQ8RzICT+JIOfCi3TGuOPgRong82KbLxg8d2Pbd13TKg4QjE6kPN6ENFQbwF/kC8TIJRWS9sO0HuI/JsLfdA5VBjMCGtjps03d7ctXiXofILhSdMMlqzbFkv8kfXKXkv+iwRvQPIOsN8ltSCFXtmgDS+O3pPz0uuwqzg00LIMNMFeJrE88WLrVB7BJyMntgUal98sQIpLzRxVgG5XlkNd+i4Fl2zAQZXeZLKhUIImygr2e0C6zhJ4xnE9Y4pMmUEscBPE3ETespV/vCDoJrv1oEOkMK9qUxhNZkNOepyy6UIDds9BYI0ZdUTsQHar+aDdlr3ad/E2mIhN773HRCxHju03UcgSuQVi7JljdV3vaiOcr3fu2lFN1bOrnDrjoAhD+A3TkcxG6FOOZ2YNw9yQiyOJiyPQ/WeRfAn8sYX0AeqrAwwiVrNaE1sTAlw6kRKA/2SKOTqSPQ39lZMUyx2jTAWSZM5tZXXxEvO3kZZNZ2a+WtZAHWhU6iamwVQWLc5/0ktzi00eHrYQ/e4u/Z4ORIgvHd9666VTbM+ARSAr/OAZAp7TM+sZMeZI6A2bXXE4KwPbwRgljLKNklSPy7zDO3S30sltwqrf3BOD9cjGThePSURxNFVabUtO/XC5M=
  on:
    tags: true
    repo: onguntoglu/pyadrc
    python: 3.8
