language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: onguntoglu
  password:
    secure: XRSTzRReO/cBkphlcFtYJaSu2GMCY3QHdx+ZNaUQwYSZES2F3wIJq6Bl8SELlsdQ1TpgBvthqYgqlMoqwMFXuEAGHJ+07QOCT9qnjrsDhQyjyiuBTWbXjtysrrM6huDVpCwE6juqkxwOsWHSmuzni/Y0ZFSzhgP/M5SGKEVecCXhVeQ9BVv875rAd9UXiRvntN/TxjQtzkiFE5bU4k9Np5fMV3V7G7K/WID21u3JBhxEBe6NHTCNxP0fNmUHAcKbR/OVKZztE2Vu0XDMV9/D3ogLDT39GijdIp61M11gwAlTvjLEB2LxLsp8ree8DpWJYhw3rZYeQ0k66edXrAwJokG6G9H/iwa6GcaBezjzthHiLYwidFrMlnzxiOBrPOxUgLwv5LHir6Z2HdNJ19yCgyZR+RLWzgV0eXdyWnc9q7R0+TjQNLAVjuLMCSblMds7+cuqBF2jybW/tZzNLqLEfW9BoSP8Vy6gU0Cqcb8xTgCxo5A9c3G9nycq69bTdgOnx3E7FRbPIgBJiptUvYMwMshYQ657uSZrdtg9BHDv4ACfbCF/WtPPV9QqUW+/LiJlwwWfN2CSZ+NlSTPKG6CMs7+j9RVDcaVEMwTI7YiBNleNCwnPgTo65+P37UDYF0Ge5zic6mLuItINv0vX/eO9JTUlSjVuZ/EK6ZD2CxabKKo=
  on:
    tags: true
    repo: onguntoglu/pyadrc
    python: 3.8
