language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: onguntoglu
  password:
    secure: JLO4+ddL05MztvDDRwgwJ/PTYp+yU7FfT0b4V5ZcctZuIs9e5FC8STYprksNz2uoGh+Eqsakvm1nHYQPvUyT8rQCfC6KH0E9HjRI06Crh4VYvwWmybcN19h5eMaivdsrsoj+HlDUnI1Oj0551Qp2lL105ZXeJrTsZy/STS3s5V2R+AkDUxFDzaAhyCPRi8qnYBM4EzppbUTcc4IR9ziNIDXBwT1UhTeKGRkp9xxms3peHKGQCVaMhCM62Uxe0LUTchpGku6/99W2HtThV3FJRMuBl0iDZdqNiWF2H3xI0fmYwTm1RyK7FpLIzdU5OrS3X6RgAavk0iek+6xCdNfRjDMzcnlvdEM5LbpSevEX0uemYq2X6rnZOaMiKbClonxHJrg1W+/BgPHuS1oA612V7QTdGEvH1l3nO2jzHv77bZ/yiyy5zl9PcUE04uBnT0bVCutG1rXxjIDb0OYb82hnwNAXPtu/TQFmIGZwojyso+t8wRVo/uXTNM78Neaord8ILyuxUBFQf2A+Uo51X0rv/XL86hv/0DqVSQBWIhc4/KvGqn3cAeWZyIrtVXO2Qt8aGHNYtEKcAg6hudkNVv22EFh6R2Vf+FbXsxi6q57lkPHSWhiv6oYZSaHSKRGekomcIHeIyRbWP1LL1vd5eFYRyzgblIMPkwfsjXGP4Ogw3Yc=
  on:
    tags: true
    repo: onguntoglu/pyadrc
    python: 3.8
